export const shopDesignCandidates=[
  {
    id:"sanibel-1001-plus-waschtisch",
    brand:"sanibel",
    title:"sanibel 1001_PLUS Waschtisch",
    category:"Bad & Sanitär",
    world:"Bad",
    mark:"01",
    visual:"basin",
    facts:["kompakte D-Form","breiter Ablagerand","von DURAVIT gefertigt"],
    sourceLabel:"Elmer Insider · 16.01.2026",
    sourceUrl:"https://insider.elmer.de/sanibel1001-plus/",
    supplierState:"Im Elmer pro beworben",
    fulfillmentState:"Direktversand zum Endkunden noch mit Elmer bestätigen"
  },
  {
    id:"sanibel-1001-plus-wc",
    brand:"sanibel",
    title:"sanibel 1001_PLUS WC",
    category:"WC & Keramik",
    world:"Bad",
    mark:"02",
    visual:"wc",
    facts:["Wand- und Standvarianten","spülrandlos","5 Jahre Garantie laut Elmer-Beitrag"],
    sourceLabel:"Elmer Insider · 16.01.2026",
    sourceUrl:"https://insider.elmer.de/sanibel1001-plus/",
    supplierState:"Im Elmer pro beworben",
    fulfillmentState:"Direktversand zum Endkunden noch mit Elmer bestätigen"
  },
  {
    id:"grohe-plus-armatur",
    brand:"GROHE",
    title:"GROHE Plus Waschtischarmatur",
    category:"Armaturen",
    world:"Bad",
    mark:"03",
    visual:"tap",
    facts:["LED-Temperaturanzeige","Eco Spray","mehrere Oberflächen"],
    sourceLabel:"Elmer Insider · GROHE Plus",
    sourceUrl:"https://insider.elmer.de/grohe-plus/",
    supplierState:"Im Elmer pro bestellbar beworben",
    fulfillmentState:"Direktversand zum Endkunden noch mit Elmer bestätigen"
  },
  {
    id:"geberit-duofix-wc-element",
    brand:"Geberit",
    title:"Geberit Duofix WC-Element",
    category:"Installation",
    world:"Installation",
    mark:"04",
    visual:"frame",
    facts:["Vorwandinstallation","optimierte Hydraulik","Profi-Systemkomponente"],
    sourceLabel:"Elmer Insider · Duofix",
    sourceUrl:"https://insider.elmer.de/page/3/",
    supplierState:"Von Elmer als Sortimentsthema geführt",
    fulfillmentState:"konkrete Artikelnummer & Direktversand noch bestätigen"
  },
  {
    id:"comfort-wps-e-speicher",
    brand:"comfort by sanibel",
    title:"WPS-E Edelstahlspeicher",
    category:"Speicher",
    world:"Haustechnik",
    mark:"05",
    visual:"storage",
    facts:["für Wärmepumpen","AISI 316L","große Wärmetauscherfläche"],
    sourceLabel:"Elmer Insider · 22.07.2026",
    sourceUrl:"https://insider.elmer.de/comfort-by-sanibel-edelstahlspeicher/",
    supplierState:"Im Elmer pro beworben",
    fulfillmentState:"Baustellen-/Endkundendirektversand noch bestätigen"
  },
  {
    id:"comfort-pumpengruppe",
    brand:"comfort by sanibel",
    title:"comfort Pumpengruppe",
    category:"Heizung & Regelung",
    world:"Haustechnik",
    mark:"06",
    visual:"pump",
    facts:["Magnetfilter integriert","Vorlauf/Rücklauf-Thermometer","gemischt & ungemischt"],
    sourceLabel:"Elmer Insider · 06.05.2026",
    sourceUrl:"https://insider.elmer.de/comfort-pumpengruppe/",
    supplierState:"Aktuelles Elmer Sortiment",
    fulfillmentState:"Direktversand zum Endkunden noch mit Elmer bestätigen"
  },
  {
    id:"grohe-rapido-heat-recovery",
    brand:"GROHE",
    title:"Rapido Duschrahmen Heat Recovery",
    category:"Dusche & Badewanne",
    world:"Effizienz",
    mark:"07",
    visual:"shower",
    facts:["Wärmerückgewinnung aus Duschwasser","Vorwand/Trockenbau","Mono- & Duo-Variante"],
    sourceLabel:"Elmer Insider · 2026",
    sourceUrl:"https://insider.elmer.de/grohe-rapido-duschrahmen-heat-recovery/",
    supplierState:"Von Elmer aktuell vorgestellt",
    fulfillmentState:"Direktversand und konkrete Variante noch bestätigen"
  },
  {
    id:"sanibel-select-duschrinne-s5",
    brand:"sanibel",
    title:"SELECT Duschrinne S5",
    category:"Dusche & Badewanne",
    world:"Bad",
    mark:"08",
    visual:"drain",
    facts:["Wand-Bodenmontage","24 mm Profilbreite","3D-Gefälle"],
    sourceLabel:"Elmer Insider · aktuelles Sortiment",
    sourceUrl:"https://insider.elmer.de/",
    supplierState:"Von Elmer aktuell vorgestellt",
    fulfillmentState:"Direktversand und Artikelvariante noch bestätigen"
  }
];
